import { resend } from "@/lib/resend";
import { getResendFromAddress, isResendConfigured } from "@/lib/email/config";

export function getBirthdayEmailTemplate(name: string): string {
  const currentYear = new Date().getFullYear();

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Happy Birthday!</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: #f8fafc; padding: 40px 20px;">
        <tr>
          <td align="center">
            <table width="100%" max-width="600px" border="0" cellspacing="0" cellpadding="0" style="max-width: 600px; background-color: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
              
              <!-- Brand Cohesive Blue Header Banner -->
              <tr>
                <td style="background-color: #2563eb; padding: 40px 30px; text-align: center;">
                  <h1 style="color: #ffffff; margin: 0; font-size: 26px; font-weight: 800; letter-spacing: -0.025em;">🎉 Happy Birthday, ${name}! 🎂</h1>
                  <p style="color: #dbeafe; margin: 8px 0 0 0; font-size: 14px;">Celebrating your special day with the SyncUp team</p>
                </td>
              </tr>

              <!-- Body Message -->
              <tr>
                <td style="padding: 40px 30px;">
                  <p style="color: #0f172a; font-size: 16px; line-height: 24px; margin: 0 0 16px 0;">Dear <strong>${name}</strong>,</p>
                  <p style="color: #475569; font-size: 14px; line-height: 22px; margin: 0 0 20px 0;">
                    On behalf of the entire team, we want to wish you a very happy and fulfilling birthday! We appreciate the dedication, creative mindset, and supportive energy you bring to our corporate workspace every day.
                  </p>
                  <p style="color: #475569; font-size: 14px; line-height: 22px; margin: 0 0 24px 0;">
                    May this next year bring you excellent health, new personal and professional milestones, and plenty of happiness. We hope you enjoy a fantastic celebration today!
                  </p>

                  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top: 1px solid #e2e8f0; padding-top: 24px;">
                    <tr>
                      <td style="text-align: center; color: #2563eb; font-weight: 700; font-size: 14px;">
                        🎈 Wishing you a successful, bright year ahead!
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

              <!-- Footer Block -->
              <tr>
                <td style="background-color: #f8fafc; padding: 24px 30px; border-top: 1px solid #e2e8f0; text-align: center;">
                  <p style="color: #94a3b8; font-size: 11px; line-height: 18px; margin: 0 0 4px 0;">This celebratory email is auto-generated by the internal HR platform.</p>
                  <p style="color: #94a3b8; font-size: 11px; line-height: 18px; margin: 0;">&copy; ${currentYear} SyncUp HR Management.</p>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
}

export async function sendBirthdayEmail(
  email: string,
  name: string,
  designation?: string,
  department?: string
): Promise<boolean> {
  void designation;
  void department;

  if (!isResendConfigured()) {
    console.error("Resend API Key (RESEND_API_KEY) is missing. Birthday email dispatch skipped.");
    return false;
  }

  try {
    const htmlContent = getBirthdayEmailTemplate(name);

    const emailResponse = await resend.emails.send({
      from: getResendFromAddress(),
      to: [email],
      subject: `Happy Birthday, ${name}! 🎂 - SyncUp Team`,
      html: htmlContent,
    });

    if (emailResponse.error) {
      console.error(`Resend birthday delivery failed for ${name}:`, emailResponse.error);
      return false;
    }

    return true;
  } catch (error) {
    console.error(`An unexpected error occurred during birthday email delivery to ${name}:`, error);
    return false;
  }
}