import { resend } from "@/lib/resend";
import { getResendFromAddress, isResendConfigured } from "@/lib/email/config";

function getPasswordResetEmailTemplate(name: string, resetUrl: string): string {
  const currentYear = new Date().getFullYear();

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Reset Your Password</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f9f8fc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: #f9f8fc; padding: 40px 20px;">
        <tr>
          <td align="center">
            <table width="100%" max-width="600px" border="0" cellspacing="0" cellpadding="0" style="max-width: 600px; background-color: #ffffff; border-radius: 16px; border: 1px solid #e2e0e8; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
              
              <!-- Branding Header Banner -->
              <tr>
                <td style="background-color: #7c3aed; padding: 40px 30px; text-align: center;">
                  <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.025em;">Password Reset Link</h1>
                  <p style="color: #ede9fe; margin: 8px 0 0 0; font-size: 14px;">Secure workspace recovery connection</p>
                </td>
              </tr>

              <!-- Body Message -->
              <tr>
                <td style="padding: 40px 30px;">
                  <p style="color: #181124; font-size: 16px; line-height: 24px; margin: 0 0 16px 0;">Hello <strong>${name}</strong>,</p>
                  <p style="color: #534a60; font-size: 14px; line-height: 22px; margin: 0 0 24px 0;">
                    We received a request to reset the password for your VibeFlow workspace account. To establish your new security credentials, click the button below:
                  </p>

                  <!-- Action Button -->
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-bottom: 28px; text-align: center;">
                    <tr>
                      <td align="center">
                        <a href="${resetUrl}" target="_blank" style="display: inline-block; background-color: #7c3aed; color: #ffffff; font-size: 14px; font-weight: 700; text-decoration: none; padding: 12px 30px; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(124, 58, 237, 0.25);">
                          Reset Workspace Password
                        </a>
                      </td>
                    </tr>
                  </table>

                  <!-- Security Protocol Alert -->
                  <table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-top: 1px solid #e2e0e8; padding-top: 24px;">
                    <tr>
                      <td>
                        <p style="color: #7c3aed; font-size: 13px; line-height: 20px; font-weight: 600; margin: 0 0 6px 0;">🔑 Password Security Info:</p>
                        <p style="color: #534a60; font-size: 13px; line-height: 20px; margin: 0;">
                          This security link is active for 60 minutes and can only be used once. If you did not authorize this request, you can safely ignore this email and your password will remain unchanged.
                        </p>
                      </td>
                    </tr>
                  </table>

                </td>
              </tr>

              <!-- Footer -->
              <tr>
                <td style="background-color: #f9f8fc; padding: 24px 30px; border-top: 1px solid #e2e0e8; text-align: center;">
                  <p style="color: #8e859c; font-size: 11px; line-height: 18px; margin: 0 0 4px 0;">This email is auto-generated by your internal HR platform. Please do not reply directly to this message.</p>
                  <p style="color: #8e859c; font-size: 11px; line-height: 18px; margin: 0;">&copy; ${currentYear} Internal Corporate Directory.</p>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
}

export async function sendPasswordResetEmail(name: string, email: string, resetUrl: string): Promise<boolean> {
  if (!isResendConfigured()) {
    console.error("Resend API Key (RESEND_API_KEY) is missing. Password reset email skipped.");
    return false;
  }

  try {
    const htmlContent = getPasswordResetEmailTemplate(name, resetUrl);

    const emailResponse = await resend.emails.send({
      from: getResendFromAddress(),
      to: [email],
      subject: "Reset Password Link - VibeFlow Workspace",
      html: htmlContent,
    });

    if (emailResponse.error) {
      console.error("Resend recovery delivery failed:", emailResponse.error);
      return false;
    }

    return true;
  } catch (error) {
    console.error("An unexpected error occurred during password reset email delivery:", error);
    return false;
  }
}